jaffle_shop:
   target: dev
   outputs:
     prod:
      type: databricks
      method: http
      schema: "jaffle_shop_prod"
      host: "adb-4283607685962842.2.azuredatabricks.net"
      http_path: "/sql/1.0/warehouses/d4bc0ffb1242fbcd"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
     dev:
      type: databricks
      method: http
      schema: "dbt_gopal__jaffle_shop"
      host: "adb-4283607685962842.2.azuredatabricks.net"
      http_path: "/sql/1.0/warehouses/d4bc0ffb1242fbcd"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"