jaffle_shop:
   target: dev
   outputs:
     prod:
      type: databricks
      method: http
      schema: "jaffle_shop_prod"
      host: "adb-2002800394447601.1.azuredatabricks.net"
      http_path: "/sql/1.0/warehouses/ef0a6fc07d996fb5"
      token: "dapib9177beac988227e0440856809ebb2e5"
     dev:
      type: databricks
      method: http
      schema: "dbt_gopal__jaffle_shop"
      host: "adb-2002800394447601.1.azuredatabricks.net"
      http_path: "/sql/1.0/warehouses/ef0a6fc07d996fb5"
      token: "dapib9177beac988227e0440856809ebb2e5"