name: "dbt_artifacts"
version: "2.4.3"
config-version: 2
require-dbt-version: [">=1.3.0", "<1.6.0"]
profile: "dbt_artifacts"

clean-targets: # folders to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_artifacts:
    +materialized: view
    +file_format: delta
    sources:
      +materialized: incremental
      +on_schema_change: append_new_columns
      +full_refresh: false
      +persist_docs:
        # Databricks doesn't offer column-level support for persisting docs
        columns: '{{ target.name != "databricks" }}'
