name: develop-code-review

on:
  pull_request:
    branches:
      - develop
env:
  PRODUCTION_BRANCH: main
  DBT_PRODUCTION_ARGS: --project-dir dags/dbt/jaffle_shop --profiles-dir dags/dbt/jaffle_shop --target prod
  TEST_BRANCH_NAME: ${{ github.head_ref }}
  DBT_TEST_ARGS: --project-dir dags/dbt/jaffle_shop --profiles-dir dags/dbt/jaffle_shop --target test
  DBT_TEST_SCHEMA: develop_pr_${{ github.event.number }}_${{ github.run_id }}_test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  dbt-code-quality-checks:
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout github repository
#        uses: actions/checkout@v2
#      - name: setup python environment
#        uses: actions/setup-python@v2
#      - name: install python dependencies
#        uses: py-actions/py-dependency-install@v4
#        with:
#          path: "ci-requirements.txt"
#      - name: run pre-commit dbt checks
#        env:
#          DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
#        run: pre-commit run --all-files
  dbt-build:
#    needs: dbt-code-quality-checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout current github repository
        uses: actions/checkout@v2
        with:
          path: current_branch
      - name: checkout github repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PRODUCTION_BRANCH }}
          path: production_branch
      - name: setup python environment
        uses: actions/setup-python@v2
      - name: install python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "current_branch/ci-requirements.txt"
      - name: compile dbt manifest in production branch
        env:
          DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
        working-directory: ./production_branch
        run: |
            dbt deps ${{ env.DBT_PRODUCTION_ARGS }}
            dbt debug ${{ env.DBT_PRODUCTION_ARGS }}
            dbt compile ${{ env.DBT_PRODUCTION_ARGS }}
            cp dags/dbt/jaffle_shop/target/manifest.json ~/
#      - name: run dbt dependencies
#        env:
#         DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
#        run: dbt deps ${{ env.DBT_ARGS }}
#      - uses: actions/checkout@v2
#        with:
#          ref: main
#          path: production
#      - name: checkout to current branch ${{ github.head_ref }}
#        run: git checkout ${{ env.CURRENT_BRANCH_NAME }}
      - name: dbt build
        env:
          DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
          DBT_TEST_SCHEMA: ${{ env.DBT_TEST_SCHEMA }}
        working-directory: ./current_branch
        run: |
          dbt deps ${{ env.DBT_TEST_ARGS }}
          dbt seed ${{ env.DBT_TEST_ARGS }}
          dbt build --models state:modified+ --defer --state ~/ ${{ env.DBT_TEST_ARGS }}
      - name: clean temporary schema
        if: always()
        env:
          DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
          DBT_TEST_SCHEMA: ${{ env.DBT_TEST_SCHEMA }}
        working-directory: ./current_branch
        run: |
          dbt run-operation pr_schema_cleanup --args "{'schema_to_clean': '${{ env.DBT_TEST_SCHEMA }}'}" ${{ env.DBT_TEST_ARGS }}
