name: develop-code-review

on:
  pull_request:
    branches:
      - develop
env:
  DBT_ARGS: --project-dir dags/dbt/jaffle_shop --profiles-dir dags/dbt/jaffle_shop --target prod
  CURRENT_BRANCH_NAME: ${{ github.head_ref }}
  PRODUCTION_BRANCH: main
jobs:
  dbt-code-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github repository
        uses: actions/checkout@v2
      - name: setup python environment
        uses: actions/setup-python@v2
      - name: install python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "ci-requirements.txt"
      - name: run pre-commit dbt checks
        env:
          DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
        run: pre-commit run --all-files
  dbt-build:
    needs: dbt-code-quality-checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup python environment
        uses: actions/setup-python@v2
      - name: install python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "ci-requirements.txt"
      - name: run dbt dependencies
        env:
          DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
        run: dbt deps ${{ env.DBT_ARGS }}
#      - uses: actions/checkout@v2
#        with:
#          ref: main
#          path: production
      - name: compile dbt manifest in production branch
        env:
          DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
        run: |
            git checkout ${{ env.PRODUCTION_BRANCH }}
            dbt debug ${{ env.DBT_ARGS }}
            dbt compile ${{ env.DBT_ARGS }}
            mv dags/dbt/jaffle_shop/target/manifest.json .
      - name: checkout to current branch ${{ github.head_ref }}
        run: git checkout ${{ env.CURRENT_BRANCH_NAME }}
      - name: dbt build
        run: dbt build --models state:modified+ --defer --state ./production ${{ env.DBT_ARGS }}
